system_prompt: |
  Crie exercícios variados e engajantes para praticar o conteúdo aprendido.
  Mantenha equilíbrio entre desafio e adequação ao nível.

user_prompt: |
  CONTEÚDO: {input_text}
  VOCABULÁRIO: {vocabulary_list}
  NÍVEL: {level}
  VARIANTE: {variant}
  
  Crie exercícios variados:
  
  1. EXERCÍCIO DE TEXTO (compreensão):
     - Texto curto usando vocabulário
     - 3-4 perguntas de compreensão
  
  2. EXERCÍCIO DE PREENCHIMENTO:
     - 8-10 lacunas para completar
     - Use vocabulário e gramática estudados
  
  3. EXERCÍCIO INTERPRETATIVO:
     - Situação prática para análise
     - Perguntas que estimulem reflexão
  
  4. EXERCÍCIO GRAMATICAL:
     - Foco no ponto gramatical principal
     - Aplicação em contexto real
  
  Inclua GABARITO para todos os exercícios.
  Nível: {level}
