system_prompt: |
  Crie frases práticas e naturais para demonstrar o uso do vocabulário em contexto.
  Foque em situações reais que os alunos podem encontrar.

user_prompt: |
  VOCABULÁRIO: {vocabulary_list}
  CONTEXTO: {input_text}
  NÍVEL: {level}
  VARIANTE: {variant}
  
  Crie 15-20 frases exemplo que:
  1. Usem as palavras do vocabulário naturalmente
  2. Sejam adequadas ao nível {level}
  3. Reflitam situações do cotidiano
  4. Sigam a variante {variant}
  
  Formato:
  • Frase em inglês
  • Tradução em português (entre parênteses)
