# ============================================================================
# config/prompts/qa_generation.yaml
# ============================================================================
system_prompt: |
  Você é um especialista em pedagogia criando perguntas e respostas baseadas na Taxonomia de Bloom.
  Sua função é desenvolver Q&A que promova aprendizado profundo e conscientização fonética.
  
  TAXONOMIA DE BLOOM (distribua as perguntas):
  1. REMEMBER: Recordar fatos e conceitos básicos
  2. UNDERSTAND: Explicar ideias e conceitos
  3. APPLY: Usar conhecimento em novas situações
  4. ANALYZE: Distinguir entre diferentes partes
  5. EVALUATE: Justificar uma posição ou decisão
  6. CREATE: Produzir trabalho novo ou original
  
  INTEGRAÇÃO FONÉTICA:
  - Inclua sempre 2-3 perguntas sobre pronúncia
  - Desenvolva consciência fonética
  - Aborde padrões de stress e ritmo

user_prompt: |
  UNIDADE: {unit_title}
  CONTEXTO: {unit_context}
  VOCABULÁRIO: {vocabulary_items}
  ESTRATÉGIA: {strategy_applied}
  NÍVEL: {cefr_level}
  VARIANTE: {language_variant}
  
  OBJETIVOS DE APRENDIZAGEM: {learning_objectives}
  FOCO FONÉTICO: {phonetic_focus}
  
  CRIE 8-12 perguntas seguindo a progressão da Taxonomia de Bloom:
  
  DISTRIBUIÇÃO SUGERIDA para {cefr_level}:
  - REMEMBER: 2-3 perguntas (vocabulário, conceitos básicos)
  - UNDERSTAND: 2-3 perguntas (explicações, descrições)
  - APPLY: 2-3 perguntas (uso em contexto)
  - ANALYZE: 1-2 perguntas (comparações, padrões)
  - EVALUATE: 1-2 perguntas (opiniões fundamentadas)
  - CREATE: 1-2 perguntas (produção original)
  
  PERGUNTAS DE PRONÚNCIA:
  - Consciência fonética dos sons
  - Padrões de stress das palavras
  - Ritmo e conectividade na fala
  
  FORMATO JSON OBRIGATÓRIO:
  {{
    "questions": [
      "What new vocabulary did you learn about hotels?",
      "How would you explain the check-in process to a friend?",
      "In what situation would you use the phrase 'I'd like to make a reservation'?",
      "Compare hotel services in your country with what you learned here.",
      "Which hotel service do you think is most important and why?",
      "Create a dialogue between a guest and hotel receptionist.",
      "How do you pronounce 'reservation'? Where is the stress?",
      "Which words from this unit have similar stress patterns?"
    ],
    "answers": [
      "Students should identify key vocabulary like reservation, check-in, reception, etc., and provide definitions in their own words.",
      "Students should describe the check-in process step by step: arrive at hotel, go to reception, provide ID, receive room key, etc.",
      "This phrase is used when booking a hotel room, restaurant table, or any advance booking situation.",
      "Students should analyze differences in service standards, technology use, and cultural practices.",
      "Students should choose a service (WiFi, breakfast, room service) and justify with personal preferences and practical reasons.",
      "Students should create an original dialogue incorporating unit vocabulary and realistic scenarios.",
      "The word 'reservation' is pronounced /ˌrezərˈveɪʃən/ with primary stress on the third syllable: reser-VA-tion.",
      "Words like information, pronunciation, and conversation follow similar stress patterns with stress on the third syllable."
    ],
    "cognitive_levels": [
      "remember", "understand", "apply", "analyze", "evaluate", "create", "remember", "analyze"
    ],
    "pedagogical_notes": [
      "Use this to assess vocabulary retention. Students should use unit vocabulary in their responses.",
      "Encourage step-by-step explanations. This develops procedural language skills.",
      "Help students connect language to real-world usage. Practice with role-play.",
      "This develops critical thinking and cultural awareness. Encourage detailed comparisons.",
      "Students practice giving opinions with justification. Focus on argument structure.",
      "This is creative application. Encourage natural dialogue with proper intonation.",
      "Focus on accurate pronunciation. Use drilling and repetition if needed.",
      "This develops phonemic awareness and pattern recognition for English stress."
    ],
    "pronunciation_questions": [
      "How do you pronounce 'reservation'? Where is the stress?",
      "Which words from this unit have similar stress patterns?",
      "What happens to the pronunciation when you say 'hotel reservation' quickly?"
    ],
    "phonetic_awareness": [
      "Students should identify primary stress on the third syllable in 'reservation'",
      "Develop awareness of English stress patterns in multi-syllable words",
      "Notice how connected speech affects pronunciation in natural conversation"
    ],
    "vocabulary_integration": [
      "reservation", "hotel", "check-in", "reception", "service", "booking"
    ],
    "difficulty_progression": "progressive"
  }}