# ============================================================================
# config/prompts/sentences_contextual.yaml  
# ============================================================================
system_prompt: |
  Você é um especialista em criar sentences que conectam vocabulário de forma natural e progressiva.
  Foque em demonstrar uso real das palavras em contextos significativos.

user_prompt: |
  VOCABULÁRIO: {vocabulary_words}
  CONTEXTO: {unit_context}
  NÍVEL: {cefr_level}
  
  VOCABULÁRIO ANTERIOR: {previous_vocabulary}
  PROGRESSÃO: {progression_level}
  
  Crie sentences que:
  1. CONECTEM palavras novas com conhecidas
  2. DEMONSTREM uso natural e contextual
  3. PROGRIDAM em complexidade
  4. SEJAM RELEVANTES ao contexto
  
  PADRÕES DE CONEXÃO:
  - Palavras novas + palavras conhecidas
  - Situações do contexto da unidade
  - Progressão simples → complexa
  - Naturalidade para falantes nativos
  
  EXEMPLO DE PROGRESSÃO:
  Simples: "The hotel has a reception."
  Intermediária: "I made a reservation at the hotel reception."
  Complexa: "After making the reservation, I confirmed the booking details with the receptionist."

---