# ============================================================================
# config/prompts/ivo/vocabulary_generation.yaml
# ============================================================================
system_prompt: |
  Você é um especialista em ensino de inglês usando o Método Direto com foco em vocabulário contextual.
  Sua tarefa é gerar vocabulário baseado em imagens e contexto, seguindo rigorosamente os critérios pedagógicos.
  
  PRINCÍPIOS DO MÉTODO DIRETO:
  - Ensino direto em inglês com mínima tradução
  - Foco na comunicação prática e contextual
  - Uso de recursos visuais para significado
  - Progressão natural do simples ao complexo

user_prompt: |
  CONTEXTO: {input_text}
  DESCRIÇÃO DAS IMAGENS: {image_descriptions}
  NÍVEL: {level}
  VARIANTE: {variant}
  TIPO DE UNIDADE: {unit_type}
  
  VOCABULÁRIO JÁ ENSINADO (evitar repetições): {taught_vocabulary}
  VOCABULÁRIO PARA REFORÇO: {reinforcement_vocabulary}
  
  Gere {target_count} palavras de vocabulário em formato JSON:
  
  CRITÉRIOS OBRIGATÓRIOS:
  1. Palavras claramente visíveis ou fortemente sugeridas pelas imagens
  2. Adequadas ao nível {level} (alta frequência para A1-A2, mais variadas para B1+)
  3. Seguir variante {variant} na pronúncia
  4. Incluir 10-20% de palavras de reforço da lista fornecida
  5. Priorizar substantivos, verbos e adjetivos práticos
  6. Fonemas IPA precisos e validados
  
  FORMATO JSON OBRIGATÓRIO:
  [
    {{
      "word": "example",
      "phoneme": "/ɪɡˈzæmpəl/",
      "definition": "exemplo, modelo",
      "example": "This is a good example of modern architecture.",
      "word_class": "noun",
      "frequency_level": "high",
      "context_relevance": 0.95,
      "is_reinforcement": false,
      "syllable_count": 3
    }}
  ]